# Extends the sdDoctrineGuard user model
sfGuardUser:
  columns:
    location:
        type: string
    hometown:
      type: string
    gender:
      type: enum
      values: [male, female]
    locale:
      type: string
    timezone:
      type: string
    facebook_id:
      type: integer(5)
      unique: true
    facebook_verified:
      type: boolean
    facebook_link:
      type: text
    facebook_location_id:
      type: integer
    facebook_hometown_id:
      type: integer